apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometurbo
  namespace: turbo
  labels:
    app: prometurbo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometurbo
    spec:
      containers:
        - name: prometurbo
          image: turbonomic/prometurbo:7.21.0
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
          volumeMounts:
          - name: prometurbo-config
            mountPath: /etc/prometurbo
            readOnly: true
          - name: varlog
            mountPath: /var/log
        - image: turbonomic/appmetric:7.21.0
          imagePullPolicy: IfNotPresent
          name: appmetric
          args:
            - --config=/etc/appmetric/appmetric.config
            - --v=2
          ports:
          - containerPort: 8081
          volumeMounts:
            - mountPath: /etc/appmetric
              name: appmetric-config
              readOnly: true
      volumes:
      - name: prometurbo-config
        configMap: 
          name: prometurbo-config
      - name: appmetric-config
        configMap:
          name: appmetric-config
      - name: varlog
        emptyDir: {}
      restartPolicy: Always

