apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometurbo
  labels:
    app: prometurbo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometurbo
  template:
    metadata:
      labels:
        app: prometurbo
    spec:
      containers:
        - name: prometurbo
          image: turbonomic/prometurbo
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
          volumeMounts:
          - name: prometurbo-config
            mountPath: /etc/prometurbo
            readOnly: true
          - name: varlog
            mountPath: /var/log
        - image: turbonomic/appmetric
          imagePullPolicy: IfNotPresent
          name: appmetric
          args:
            - --promUrl=http://prometheus.istio-system:9090
            - --v=2
          ports:
          - containerPort: 8081
          volumeMounts:
            - name: appmetric-config
              mountPath: /etc/appmetric
              readOnly: true
      volumes:
      - name: prometurbo-config
        configMap: 
          name: prometurbo-config
      - name: appmetric-config
        configMap:
          name: appmetric-config
      - name: varlog
        emptyDir: {}
      restartPolicy: Always

