[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/turbonomic/turbo-go-sdk"

[prune]
  go-tests = true
  unused-packages = true
