apiVersion: charts.helm.k8s.io/v1
kind: Prometurbo
metadata:
  name: prometurbo-release
spec:
  # Prometheus servers and metrics to scrape
  prometheusServers: |
    server1:
      # The URL of the prometheus server
      url: https://Prometheus_Server_URL
      # The list of supported exporters for the above prometheus server
      exporters:
        - cassandra
        - istio
        - jmx-tomcat
        - node
        - redis
        - webdriver

  # Turbo server version and address
  serverMeta:
    turboServer: https://Turbo_server_URL

  # Turbo server api user and password stored in a secret or optionally specified as username and password
  # The opsManagerUserName requires Turbo administrator role
  #restAPIConfig:
    #turbonomicCredentialsSecretName: "turbonomic-credentials"
    #opsManagerUserName: Turbo_username
    #opsManagerPassword: Turbo_password

  # Configurations to register probe with Turbo Server
  sdkProtocolConfig:
    registrationTimeoutSec: 300
    restartOnRegistrationTimeout: false

  # Specify a unique target name, defaults to Prometheus
  #targetName: Prometheus

  # Specify a unique target type suffix, defaults to Prometheus
  # The Target Type will appear as DataIngestionFramework-<targetTypeSuffix> on the UI
  # Do not specify Turbonomic as the targetTypeSuffix, it is reserved for internal use
  #targetTypeSuffix: Prometheus

  # Command line arguments
  args:
    # Logging level 2 to 4
    logginglevel: 2
    # When set to true, ignore merging a commodity if a commodity of the same type already exists
    #ignoreCommodityIfPresent: false
